/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_raonix_effect4dapp_HA210_ApkInfo */

#ifndef _Included_com_raonix_effect4dapp_HA210_ApkInfo
#define _Included_com_raonix_effect4dapp_HA210_ApkInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
