/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_raonix_effect4dapp_HA210_PInfo */

#ifndef _Included_com_raonix_effect4dapp_HA210_PInfo
#define _Included_com_raonix_effect4dapp_HA210_PInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
