/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_raonix_effect4dapp_HA210_InstallAndRebootThread */

#ifndef _Included_com_raonix_effect4dapp_HA210_InstallAndRebootThread
#define _Included_com_raonix_effect4dapp_HA210_InstallAndRebootThread
#ifdef __cplusplus
extern "C" {
#endif
#undef com_raonix_effect4dapp_HA210_InstallAndRebootThread_MIN_PRIORITY
#define com_raonix_effect4dapp_HA210_InstallAndRebootThread_MIN_PRIORITY 1L
#undef com_raonix_effect4dapp_HA210_InstallAndRebootThread_NORM_PRIORITY
#define com_raonix_effect4dapp_HA210_InstallAndRebootThread_NORM_PRIORITY 5L
#undef com_raonix_effect4dapp_HA210_InstallAndRebootThread_MAX_PRIORITY
#define com_raonix_effect4dapp_HA210_InstallAndRebootThread_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
