/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_raonix_effect4dapp_HA210 */

#ifndef _Included_com_raonix_effect4dapp_HA210
#define _Included_com_raonix_effect4dapp_HA210
#ifdef __cplusplus
extern "C" {
#endif
#undef com_raonix_effect4dapp_HA210_HAUTO_EVENT
#define com_raonix_effect4dapp_HA210_HAUTO_EVENT 0L
#undef com_raonix_effect4dapp_HA210_INTERPHONE_EVENT
#define com_raonix_effect4dapp_HA210_INTERPHONE_EVENT 1L
#undef com_raonix_effect4dapp_HA210_SYSTEM_EVENT
#define com_raonix_effect4dapp_HA210_SYSTEM_EVENT 2L
#undef com_raonix_effect4dapp_HA210_SECURITY_EVENT
#define com_raonix_effect4dapp_HA210_SECURITY_EVENT 3L
#undef com_raonix_effect4dapp_HA210_STATE_IDLE
#define com_raonix_effect4dapp_HA210_STATE_IDLE 0L
#undef com_raonix_effect4dapp_HA210_STATE_DOWNLOAD
#define com_raonix_effect4dapp_HA210_STATE_DOWNLOAD 1L
#undef com_raonix_effect4dapp_HA210_UPDATE_CHECK_SYSTEM
#define com_raonix_effect4dapp_HA210_UPDATE_CHECK_SYSTEM 0L
#undef com_raonix_effect4dapp_HA210_UPDATE_CHECK_APK
#define com_raonix_effect4dapp_HA210_UPDATE_CHECK_APK 1L
#undef com_raonix_effect4dapp_HA210_UPDATE_DOWNLOAD_SYSTEM
#define com_raonix_effect4dapp_HA210_UPDATE_DOWNLOAD_SYSTEM 2L
#undef com_raonix_effect4dapp_HA210_UPDATE_DOWNLOAD_APK
#define com_raonix_effect4dapp_HA210_UPDATE_DOWNLOAD_APK 3L
#undef com_raonix_effect4dapp_HA210_UPDATE_DOWNLOAD_SYSTEM_DONE
#define com_raonix_effect4dapp_HA210_UPDATE_DOWNLOAD_SYSTEM_DONE 4L
#undef com_raonix_effect4dapp_HA210_UPDATE_DOWNLOAD_APK_DONE
#define com_raonix_effect4dapp_HA210_UPDATE_DOWNLOAD_APK_DONE 5L
/*
 * Class:     com_raonix_effect4dapp_HA210
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_raonix_effect4dapp_HA210_nativeInit
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_raonix_effect4dapp_HA210
 * Method:    nativeRelease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_raonix_effect4dapp_HA210_nativeRelease
  (JNIEnv *, jobject);

/*
 * Class:     com_raonix_effect4dapp_HA210
 * Method:    nativeHAutoDeviceSetNum
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_raonix_effect4dapp_HA210_nativeHAutoDeviceSetNum
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_raonix_effect4dapp_HA210
 * Method:    nativeHAutoLightScan
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_raonix_effect4dapp_HA210_nativeHAutoLightScan
  (JNIEnv *, jobject);

/*
 * Class:     com_raonix_effect4dapp_HA210
 * Method:    nativeHAutoLightGetState
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_raonix_effect4dapp_HA210_nativeHAutoLightGetState
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     com_raonix_effect4dapp_HA210
 * Method:    nativeHAutoLightGetCharacter
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_raonix_effect4dapp_HA210_nativeHAutoLightGetCharacter
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     com_raonix_effect4dapp_HA210
 * Method:    nativeHAutoLightSetOne
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_raonix_effect4dapp_HA210_nativeHAutoLightSetOne
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_raonix_effect4dapp_HA210
 * Method:    nativeHAutoLightSetAll
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_raonix_effect4dapp_HA210_nativeHAutoLightSetAll
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_raonix_effect4dapp_HA210
 * Method:    nativeHAutoPlayerScan
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_raonix_effect4dapp_HA210_nativeHAutoPlayerScan
  (JNIEnv *, jobject);

/*
 * Class:     com_raonix_effect4dapp_HA210
 * Method:    nativeHAutoPlayerGetState
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_raonix_effect4dapp_HA210_nativeHAutoPlayerGetState
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     com_raonix_effect4dapp_HA210
 * Method:    nativeHAutoPlayerGetCharacter
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_raonix_effect4dapp_HA210_nativeHAutoPlayerGetCharacter
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     com_raonix_effect4dapp_HA210
 * Method:    nativeHAutoPlayerSet
 * Signature: (III[BI)I
 */
JNIEXPORT jint JNICALL Java_com_raonix_effect4dapp_HA210_nativeHAutoPlayerSet
  (JNIEnv *, jobject, jint, jint, jint, jbyteArray, jint);

/*
 * Class:     com_raonix_effect4dapp_HA210
 * Method:    nativeHAutoMotorControllerScan
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_raonix_effect4dapp_HA210_nativeHAutoMotorControllerScan
  (JNIEnv *, jobject);

/*
 * Class:     com_raonix_effect4dapp_HA210
 * Method:    nativeHAutoMotorControllerGetState
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_raonix_effect4dapp_HA210_nativeHAutoMotorControllerGetState
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     com_raonix_effect4dapp_HA210
 * Method:    nativeHAutoMotorControllerGetCharacter
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_raonix_effect4dapp_HA210_nativeHAutoMotorControllerGetCharacter
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     com_raonix_effect4dapp_HA210
 * Method:    nativeHAutoMotorControllerSet
 * Signature: (III[BI)I
 */
JNIEXPORT jint JNICALL Java_com_raonix_effect4dapp_HA210_nativeHAutoMotorControllerSet
  (JNIEnv *, jobject, jint, jint, jint, jbyteArray, jint);

/*
 * Class:     com_raonix_effect4dapp_HA210
 * Method:    nativeHAutoIOScan
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_raonix_effect4dapp_HA210_nativeHAutoIOScan
  (JNIEnv *, jobject);

/*
 * Class:     com_raonix_effect4dapp_HA210
 * Method:    nativeHAutoIOGetState
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_raonix_effect4dapp_HA210_nativeHAutoIOGetState
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     com_raonix_effect4dapp_HA210
 * Method:    nativeHAutoIOGetCharacter
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_raonix_effect4dapp_HA210_nativeHAutoIOGetCharacter
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     com_raonix_effect4dapp_HA210
 * Method:    nativeHAutoIOSetRelay
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_raonix_effect4dapp_HA210_nativeHAutoIOSetRelay
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_raonix_effect4dapp_HA210
 * Method:    nativeSystemHWWatchdogEnable
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_raonix_effect4dapp_HA210_nativeSystemHWWatchdogEnable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_raonix_effect4dapp_HA210
 * Method:    nativeSystemHWWatchdogRefresh
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_raonix_effect4dapp_HA210_nativeSystemHWWatchdogRefresh
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
